import type { RecurringPaymentCadence } from "@/lib/payments/types";

export type StarterPaymentTemplate = {
  id: string;
  label: string;
  scenario: "personal" | "family";
  title: string;
  category: string;
  cadence: RecurringPaymentCadence;
  currency: string;
  dueDay: number;
  isRequired: boolean;
  isSubscription: boolean;
  remindersEnabled: boolean;
  remindDaysBefore: 0 | 1 | 3;
  remindOnDueDay: boolean;
  remindOnOverdue: boolean;
  notes: string;
};

export const personalStarterPaymentTemplates: StarterPaymentTemplate[] = [
  {
    id: "internet",
    label: "Internet",
    scenario: "personal",
    title: "Home Internet",
    category: "Internet",
    cadence: "monthly",
    currency: "USD",
    dueDay: 5,
    isRequired: true,
    isSubscription: true,
    remindersEnabled: true,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "mobile",
    label: "Mobile",
    scenario: "personal",
    title: "Mobile Plan",
    category: "Mobile",
    cadence: "monthly",
    currency: "USD",
    dueDay: 10,
    isRequired: true,
    isSubscription: true,
    remindersEnabled: true,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "rent",
    label: "Rent",
    scenario: "personal",
    title: "Apartment Rent",
    category: "Housing",
    cadence: "monthly",
    currency: "USD",
    dueDay: 1,
    isRequired: true,
    isSubscription: false,
    remindersEnabled: true,
    remindDaysBefore: 3,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "utilities",
    label: "Utilities",
    scenario: "personal",
    title: "Utilities Bill",
    category: "Utilities",
    cadence: "monthly",
    currency: "USD",
    dueDay: 15,
    isRequired: true,
    isSubscription: false,
    remindersEnabled: true,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "gym",
    label: "Gym",
    scenario: "personal",
    title: "Gym Membership",
    category: "Health",
    cadence: "monthly",
    currency: "USD",
    dueDay: 3,
    isRequired: false,
    isSubscription: true,
    remindersEnabled: false,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: false,
    notes: "",
  },
  {
    id: "streaming",
    label: "Streaming",
    scenario: "personal",
    title: "Streaming Service",
    category: "Entertainment",
    cadence: "monthly",
    currency: "USD",
    dueDay: 7,
    isRequired: false,
    isSubscription: true,
    remindersEnabled: false,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: false,
    notes: "",
  },
  {
    id: "loan",
    label: "Loan",
    scenario: "personal",
    title: "Loan Payment",
    category: "Debt",
    cadence: "monthly",
    currency: "USD",
    dueDay: 12,
    isRequired: true,
    isSubscription: false,
    remindersEnabled: true,
    remindDaysBefore: 3,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "insurance",
    label: "Insurance",
    scenario: "personal",
    title: "Insurance Premium",
    category: "Insurance",
    cadence: "monthly",
    currency: "USD",
    dueDay: 25,
    isRequired: true,
    isSubscription: true,
    remindersEnabled: true,
    remindDaysBefore: 3,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
];

export const familyStarterPaymentTemplates: StarterPaymentTemplate[] = [
  {
    id: "shared-rent",
    label: "Shared rent",
    scenario: "family",
    title: "Family Rent",
    category: "Housing",
    cadence: "monthly",
    currency: "USD",
    dueDay: 1,
    isRequired: true,
    isSubscription: false,
    remindersEnabled: true,
    remindDaysBefore: 3,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "groceries",
    label: "Groceries",
    scenario: "family",
    title: "Family Groceries",
    category: "Food",
    cadence: "weekly",
    currency: "USD",
    dueDay: 6,
    isRequired: true,
    isSubscription: false,
    remindersEnabled: true,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "school",
    label: "School",
    scenario: "family",
    title: "School Fee",
    category: "Education",
    cadence: "monthly",
    currency: "USD",
    dueDay: 8,
    isRequired: true,
    isSubscription: false,
    remindersEnabled: true,
    remindDaysBefore: 3,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "shared-internet",
    label: "Home internet",
    scenario: "family",
    title: "Shared Internet",
    category: "Internet",
    cadence: "monthly",
    currency: "USD",
    dueDay: 5,
    isRequired: true,
    isSubscription: true,
    remindersEnabled: true,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "shared-streaming",
    label: "Family streaming",
    scenario: "family",
    title: "Family Streaming",
    category: "Entertainment",
    cadence: "monthly",
    currency: "USD",
    dueDay: 12,
    isRequired: false,
    isSubscription: true,
    remindersEnabled: false,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: false,
    notes: "",
  },
  {
    id: "electricity",
    label: "Electricity",
    scenario: "family",
    title: "Electricity Bill",
    category: "Utilities",
    cadence: "monthly",
    currency: "USD",
    dueDay: 20,
    isRequired: true,
    isSubscription: false,
    remindersEnabled: true,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
];

export const starterPaymentTemplates: StarterPaymentTemplate[] = [
  ...personalStarterPaymentTemplates,
  ...familyStarterPaymentTemplates,
];
