import type { RecurringPaymentCadence } from "@/lib/payments/types";

export type StarterPaymentTemplate = {
  id: string;
  label: string;
  title: string;
  category: string;
  cadence: RecurringPaymentCadence;
  currency: string;
  dueDay: number;
  isRequired: boolean;
  isSubscription: boolean;
  remindersEnabled: boolean;
  remindDaysBefore: 0 | 1 | 3;
  remindOnDueDay: boolean;
  remindOnOverdue: boolean;
  notes: string;
};

export const starterPaymentTemplates: StarterPaymentTemplate[] = [
  {
    id: "internet",
    label: "Internet",
    title: "Home Internet",
    category: "Internet",
    cadence: "monthly",
    currency: "USD",
    dueDay: 5,
    isRequired: true,
    isSubscription: true,
    remindersEnabled: true,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "mobile",
    label: "Mobile",
    title: "Mobile Plan",
    category: "Mobile",
    cadence: "monthly",
    currency: "USD",
    dueDay: 10,
    isRequired: true,
    isSubscription: true,
    remindersEnabled: true,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "rent",
    label: "Rent",
    title: "Apartment Rent",
    category: "Housing",
    cadence: "monthly",
    currency: "USD",
    dueDay: 1,
    isRequired: true,
    isSubscription: false,
    remindersEnabled: true,
    remindDaysBefore: 3,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "utilities",
    label: "Utilities",
    title: "Utilities Bill",
    category: "Utilities",
    cadence: "monthly",
    currency: "USD",
    dueDay: 15,
    isRequired: true,
    isSubscription: false,
    remindersEnabled: true,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "water",
    label: "Water",
    title: "Water Bill",
    category: "Utilities",
    cadence: "monthly",
    currency: "USD",
    dueDay: 18,
    isRequired: true,
    isSubscription: false,
    remindersEnabled: true,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "electricity",
    label: "Electricity",
    title: "Electricity Bill",
    category: "Utilities",
    cadence: "monthly",
    currency: "USD",
    dueDay: 20,
    isRequired: true,
    isSubscription: false,
    remindersEnabled: true,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "gym",
    label: "Gym",
    title: "Gym Membership",
    category: "Health",
    cadence: "monthly",
    currency: "USD",
    dueDay: 3,
    isRequired: false,
    isSubscription: true,
    remindersEnabled: false,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: false,
    notes: "",
  },
  {
    id: "streaming",
    label: "Streaming",
    title: "Streaming Service",
    category: "Entertainment",
    cadence: "monthly",
    currency: "USD",
    dueDay: 7,
    isRequired: false,
    isSubscription: true,
    remindersEnabled: false,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: false,
    notes: "",
  },
  {
    id: "loan",
    label: "Loan",
    title: "Loan Payment",
    category: "Debt",
    cadence: "monthly",
    currency: "USD",
    dueDay: 12,
    isRequired: true,
    isSubscription: false,
    remindersEnabled: true,
    remindDaysBefore: 3,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
  {
    id: "insurance",
    label: "Insurance",
    title: "Insurance Premium",
    category: "Insurance",
    cadence: "monthly",
    currency: "USD",
    dueDay: 25,
    isRequired: true,
    isSubscription: true,
    remindersEnabled: true,
    remindDaysBefore: 3,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
  },
];
