import type { RecurringPaymentCadence } from "@/lib/payments/types";

export type StarterPaymentTemplate = {
  id: string;
  label: string;
  scenario: "personal" | "family";
  title: string;
  category: string;
  cadence: RecurringPaymentCadence;
  currency: string;
  dueDay: number;
  isRequired: boolean;
  isSubscription: boolean;
  remindersEnabled: boolean;
  remindDaysBefore: 0 | 1 | 3;
  remindOnDueDay: boolean;
  remindOnOverdue: boolean;
  notes: string;
};

type StarterTemplateInput = Omit<
  StarterPaymentTemplate,
  | "currency"
  | "remindersEnabled"
  | "remindDaysBefore"
  | "remindOnDueDay"
  | "remindOnOverdue"
  | "notes"
> &
  Partial<
    Pick<
      StarterPaymentTemplate,
      | "currency"
      | "remindersEnabled"
      | "remindDaysBefore"
      | "remindOnDueDay"
      | "remindOnOverdue"
      | "notes"
    >
  >;

const createStarterTemplate = (
  input: StarterTemplateInput,
): StarterPaymentTemplate => {
  return {
    currency: "RUB",
    remindersEnabled: true,
    remindDaysBefore: 1,
    remindOnDueDay: true,
    remindOnOverdue: true,
    notes: "",
    ...input,
  };
};

export const personalStarterPaymentTemplates: StarterPaymentTemplate[] = [
  createStarterTemplate({
    id: "internet",
    label: "Home internet",
    scenario: "personal",
    title: "Home Internet",
    category: "Internet",
    cadence: "monthly",
    dueDay: 5,
    isRequired: true,
    isSubscription: true,
  }),
  createStarterTemplate({
    id: "mobile",
    label: "Mobile plan",
    scenario: "personal",
    title: "Mobile Plan",
    category: "Mobile",
    cadence: "monthly",
    dueDay: 10,
    isRequired: true,
    isSubscription: true,
  }),
  createStarterTemplate({
    id: "rent",
    label: "Rent",
    scenario: "personal",
    title: "Apartment Rent",
    category: "Housing",
    cadence: "monthly",
    dueDay: 1,
    isRequired: true,
    isSubscription: false,
    remindDaysBefore: 3,
  }),
  createStarterTemplate({
    id: "mortgage",
    label: "Mortgage",
    scenario: "personal",
    title: "Mortgage Payment",
    category: "Housing",
    cadence: "monthly",
    dueDay: 2,
    isRequired: true,
    isSubscription: false,
    remindDaysBefore: 3,
  }),
  createStarterTemplate({
    id: "utilities",
    label: "Utilities",
    scenario: "personal",
    title: "Utilities Bill",
    category: "Utilities",
    cadence: "monthly",
    dueDay: 15,
    isRequired: true,
    isSubscription: false,
  }),
  createStarterTemplate({
    id: "electricity",
    label: "Electricity",
    scenario: "personal",
    title: "Electricity Bill",
    category: "Utilities",
    cadence: "monthly",
    dueDay: 20,
    isRequired: true,
    isSubscription: false,
  }),
  createStarterTemplate({
    id: "water",
    label: "Water",
    scenario: "personal",
    title: "Water Bill",
    category: "Utilities",
    cadence: "monthly",
    dueDay: 21,
    isRequired: true,
    isSubscription: false,
  }),
  createStarterTemplate({
    id: "gas",
    label: "Gas",
    scenario: "personal",
    title: "Gas Bill",
    category: "Utilities",
    cadence: "monthly",
    dueDay: 23,
    isRequired: true,
    isSubscription: false,
  }),
  createStarterTemplate({
    id: "groceries",
    label: "Groceries",
    scenario: "personal",
    title: "Groceries Budget",
    category: "Food",
    cadence: "weekly",
    dueDay: 6,
    isRequired: true,
    isSubscription: false,
  }),
  createStarterTemplate({
    id: "transport-pass",
    label: "Public transport",
    scenario: "personal",
    title: "Transport Pass",
    category: "Transport",
    cadence: "monthly",
    dueDay: 4,
    isRequired: true,
    isSubscription: true,
    remindDaysBefore: 0,
  }),
  createStarterTemplate({
    id: "fuel",
    label: "Fuel",
    scenario: "personal",
    title: "Fuel Refill",
    category: "Transport",
    cadence: "weekly",
    dueDay: 5,
    isRequired: false,
    isSubscription: false,
    remindDaysBefore: 0,
  }),
  createStarterTemplate({
    id: "parking",
    label: "Parking",
    scenario: "personal",
    title: "Parking Permit",
    category: "Transport",
    cadence: "monthly",
    dueDay: 11,
    isRequired: false,
    isSubscription: true,
    remindDaysBefore: 0,
  }),
  createStarterTemplate({
    id: "pharmacy",
    label: "Pharmacy",
    scenario: "personal",
    title: "Pharmacy and Medicine",
    category: "Health",
    cadence: "monthly",
    dueDay: 18,
    isRequired: true,
    isSubscription: false,
  }),
  createStarterTemplate({
    id: "gym",
    label: "Gym and sports",
    scenario: "personal",
    title: "Gym Membership",
    category: "Health",
    cadence: "monthly",
    dueDay: 3,
    isRequired: false,
    isSubscription: true,
    remindersEnabled: false,
    remindOnOverdue: false,
  }),
  createStarterTemplate({
    id: "insurance",
    label: "Insurance",
    scenario: "personal",
    title: "Insurance payment",
    category: "Insurance",
    cadence: "monthly",
    dueDay: 25,
    isRequired: true,
    isSubscription: true,
    remindDaysBefore: 3,
  }),
  createStarterTemplate({
    id: "loan",
    label: "Loan",
    scenario: "personal",
    title: "Loan Payment",
    category: "Debt",
    cadence: "monthly",
    dueDay: 12,
    isRequired: true,
    isSubscription: false,
    remindDaysBefore: 3,
  }),
  createStarterTemplate({
    id: "bank-fee",
    label: "Bank fee",
    scenario: "personal",
    title: "Bank Service Fee",
    category: "Banking",
    cadence: "monthly",
    dueDay: 28,
    isRequired: false,
    isSubscription: true,
    remindersEnabled: false,
    remindDaysBefore: 0,
    remindOnOverdue: false,
  }),
  createStarterTemplate({
    id: "streaming",
    label: "Streaming",
    scenario: "personal",
    title: "Streaming Service",
    category: "Entertainment",
    cadence: "monthly",
    dueDay: 7,
    isRequired: false,
    isSubscription: true,
    remindersEnabled: false,
    remindOnOverdue: false,
  }),
  createStarterTemplate({
    id: "gaming",
    label: "Gaming",
    scenario: "personal",
    title: "Gaming Subscription",
    category: "Entertainment",
    cadence: "monthly",
    dueDay: 9,
    isRequired: false,
    isSubscription: true,
    remindersEnabled: false,
    remindOnOverdue: false,
  }),
  createStarterTemplate({
    id: "cloud",
    label: "Cloud storage",
    scenario: "personal",
    title: "Cloud Storage",
    category: "Digital services",
    cadence: "monthly",
    dueDay: 14,
    isRequired: false,
    isSubscription: true,
    remindersEnabled: false,
    remindOnOverdue: false,
  }),
  createStarterTemplate({
    id: "pet-care",
    label: "Pet care",
    scenario: "personal",
    title: "Pet Food Subscription",
    category: "Pet care",
    cadence: "monthly",
    dueDay: 17,
    isRequired: false,
    isSubscription: true,
    remindersEnabled: false,
    remindOnOverdue: false,
  }),
  createStarterTemplate({
    id: "home-cleaning",
    label: "Home cleaning",
    scenario: "personal",
    title: "Home Cleaning Service",
    category: "Household services",
    cadence: "monthly",
    dueDay: 24,
    isRequired: false,
    isSubscription: false,
    remindersEnabled: false,
    remindDaysBefore: 0,
    remindOnOverdue: false,
  }),
];

export const familyStarterPaymentTemplates: StarterPaymentTemplate[] = [
  createStarterTemplate({
    id: "shared-rent",
    label: "Shared rent",
    scenario: "family",
    title: "Family Rent",
    category: "Housing",
    cadence: "monthly",
    dueDay: 1,
    isRequired: true,
    isSubscription: false,
    remindDaysBefore: 3,
  }),
  createStarterTemplate({
    id: "family-mortgage",
    label: "Family mortgage",
    scenario: "family",
    title: "Family Mortgage",
    category: "Housing",
    cadence: "monthly",
    dueDay: 2,
    isRequired: true,
    isSubscription: false,
    remindDaysBefore: 3,
  }),
  createStarterTemplate({
    id: "groceries",
    label: "Groceries",
    scenario: "family",
    title: "Family Groceries",
    category: "Food",
    cadence: "weekly",
    dueDay: 6,
    isRequired: true,
    isSubscription: false,
  }),
  createStarterTemplate({
    id: "school",
    label: "School",
    scenario: "family",
    title: "School Fee",
    category: "Education",
    cadence: "monthly",
    dueDay: 8,
    isRequired: true,
    isSubscription: false,
    remindDaysBefore: 3,
  }),
  createStarterTemplate({
    id: "kindergarten",
    label: "Kindergarten",
    scenario: "family",
    title: "Kindergarten Fee",
    category: "Education",
    cadence: "monthly",
    dueDay: 9,
    isRequired: true,
    isSubscription: false,
    remindDaysBefore: 3,
  }),
  createStarterTemplate({
    id: "children-club",
    label: "Children club",
    scenario: "family",
    title: "Children Club",
    category: "Children activities",
    cadence: "monthly",
    dueDay: 11,
    isRequired: false,
    isSubscription: true,
  }),
  createStarterTemplate({
    id: "children-sports",
    label: "Children sports",
    scenario: "family",
    title: "Children Sports Section",
    category: "Children activities",
    cadence: "monthly",
    dueDay: 13,
    isRequired: false,
    isSubscription: true,
  }),
  createStarterTemplate({
    id: "children-tutor",
    label: "Tutor",
    scenario: "family",
    title: "Tutor Payments",
    category: "Education",
    cadence: "monthly",
    dueDay: 16,
    isRequired: false,
    isSubscription: false,
  }),
  createStarterTemplate({
    id: "shared-internet",
    label: "Home internet",
    scenario: "family",
    title: "Shared Internet",
    category: "Internet",
    cadence: "monthly",
    dueDay: 5,
    isRequired: true,
    isSubscription: true,
  }),
  createStarterTemplate({
    id: "family-mobile",
    label: "Family mobile",
    scenario: "family",
    title: "Family Mobile Plan",
    category: "Mobile",
    cadence: "monthly",
    dueDay: 10,
    isRequired: true,
    isSubscription: true,
  }),
  createStarterTemplate({
    id: "electricity",
    label: "Electricity",
    scenario: "family",
    title: "Electricity Bill",
    category: "Utilities",
    cadence: "monthly",
    dueDay: 20,
    isRequired: true,
    isSubscription: false,
  }),
  createStarterTemplate({
    id: "water",
    label: "Water",
    scenario: "family",
    title: "Water Bill",
    category: "Utilities",
    cadence: "monthly",
    dueDay: 21,
    isRequired: true,
    isSubscription: false,
  }),
  createStarterTemplate({
    id: "gas",
    label: "Gas",
    scenario: "family",
    title: "Gas Bill",
    category: "Utilities",
    cadence: "monthly",
    dueDay: 23,
    isRequired: true,
    isSubscription: false,
  }),
  createStarterTemplate({
    id: "family-transport",
    label: "Family transport",
    scenario: "family",
    title: "Public Transport Cards",
    category: "Transport",
    cadence: "monthly",
    dueDay: 6,
    isRequired: true,
    isSubscription: true,
    remindDaysBefore: 0,
  }),
  createStarterTemplate({
    id: "family-fuel",
    label: "Fuel",
    scenario: "family",
    title: "Family Fuel",
    category: "Transport",
    cadence: "weekly",
    dueDay: 5,
    isRequired: false,
    isSubscription: false,
    remindDaysBefore: 0,
  }),
  createStarterTemplate({
    id: "family-insurance",
    label: "Family insurance",
    scenario: "family",
    title: "Family Insurance",
    category: "Insurance",
    cadence: "monthly",
    dueDay: 25,
    isRequired: true,
    isSubscription: true,
    remindDaysBefore: 3,
  }),
  createStarterTemplate({
    id: "shared-streaming",
    label: "Family streaming",
    scenario: "family",
    title: "Family Streaming",
    category: "Entertainment",
    cadence: "monthly",
    dueDay: 12,
    isRequired: false,
    isSubscription: true,
    remindersEnabled: false,
    remindOnOverdue: false,
  }),
  createStarterTemplate({
    id: "family-gaming",
    label: "Family gaming",
    scenario: "family",
    title: "Family Gaming Subscription",
    category: "Entertainment",
    cadence: "monthly",
    dueDay: 18,
    isRequired: false,
    isSubscription: true,
    remindersEnabled: false,
    remindOnOverdue: false,
  }),
  createStarterTemplate({
    id: "family-pharmacy",
    label: "Family pharmacy",
    scenario: "family",
    title: "Family Pharmacy",
    category: "Health",
    cadence: "monthly",
    dueDay: 19,
    isRequired: true,
    isSubscription: false,
  }),
  createStarterTemplate({
    id: "pet-care-family",
    label: "Pet care",
    scenario: "family",
    title: "Family Pet Care",
    category: "Pet care",
    cadence: "monthly",
    dueDay: 17,
    isRequired: false,
    isSubscription: false,
    remindersEnabled: false,
    remindDaysBefore: 0,
    remindOnOverdue: false,
  }),
  createStarterTemplate({
    id: "household-services",
    label: "Household services",
    scenario: "family",
    title: "Household Services",
    category: "Household services",
    cadence: "monthly",
    dueDay: 24,
    isRequired: false,
    isSubscription: false,
    remindersEnabled: false,
    remindDaysBefore: 0,
    remindOnOverdue: false,
  }),
  createStarterTemplate({
    id: "family-bank-fee",
    label: "Family bank fees",
    scenario: "family",
    title: "Family Bank Service Fee",
    category: "Banking",
    cadence: "monthly",
    dueDay: 28,
    isRequired: false,
    isSubscription: true,
    remindersEnabled: false,
    remindDaysBefore: 0,
    remindOnOverdue: false,
  }),
];

export const starterPaymentTemplates: StarterPaymentTemplate[] = [
  ...personalStarterPaymentTemplates,
  ...familyStarterPaymentTemplates,
];
